---
- name: Gather Architecture specific variables
  ansible.builtin.include_vars: 'os-architecture/{{ ansible_system }}-{{ ansible_architecture }}.yml'

- name: Include role mesaguy.prometheus common task
  ansible.builtin.include_tasks: _common.yml

- name: Define setup as complete
  ansible.builtin.set_fact:
    prometheus_setup_task_executed: true
